// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NbaDb.Data;

namespace NbaDb.Migrations
{
    [DbContext(typeof(NbaDbContext))]
    [Migration("20190414061935_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NbaDb.Models.GamesPlayed", b =>
                {
                    b.Property<int>("PlayerId");

                    b.Property<double>("GP");

                    b.HasKey("PlayerId");

                    b.ToTable("GamesPlayed");
                });

            modelBuilder.Entity("NbaDb.Models.Player", b =>
                {
                    b.Property<int>("Id");

                    b.Property<double>("AST");

                    b.Property<double>("BLK");

                    b.Property<double>("DREB");

                    b.Property<double>("FG3A");

                    b.Property<double>("FGA");

                    b.Property<double>("FTA");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<double>("MIN");

                    b.Property<double>("OREB");

                    b.Property<double>("PF");

                    b.Property<double>("PTS");

                    b.Property<double>("STL");

                    b.Property<double>("TOV");

                    b.Property<double>("W_PCT");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("NbaDb.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Team");
                });

            modelBuilder.Entity("NbaDb.Models.TeamPlayer", b =>
                {
                    b.Property<int>("PlayerId");

                    b.Property<int>("TeamId");

                    b.HasKey("PlayerId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPlayer");
                });

            modelBuilder.Entity("NbaDb.Models.GamesPlayed", b =>
                {
                    b.HasOne("NbaDb.Models.Player", "Player")
                        .WithOne("GamesPlayed")
                        .HasForeignKey("NbaDb.Models.GamesPlayed", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NbaDb.Models.TeamPlayer", b =>
                {
                    b.HasOne("NbaDb.Models.Player", "Player")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NbaDb.Models.Team", "Team")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
